# To install these hooks:
#
#   1. The pre-commit package is installed when you use
#         `pip install -f requirements.txt` to install dependencies.
#   2. From the repository root directory, run `pre-commit install`.
#   3. Verify all the pre-commit tests pass, run `pre-commit run --all-files`.

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb=100000"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types: [yaml]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.381
    hooks:
      - id: pyright
        verbose: false
